name: RSS Feed Cron Job

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  rss-feed-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run RSS feed cron job
        run: node rss-feed-cron-job.js
